### ISSUE TITLE
fix the unavailable images

### ISSUE THREAD

**Issue by JVJplus** [JVJplus/Emoji-Cart-With-React#4]
the buttons to add, minus and delete are not visible as the src link is changed. Update the src link with updated link or use static images.

**Comment by dikshantsagar12** [comment]
Hi,
Is anyone working on this? If not, can I give it a try?

**Comment by JVJplus** [comment]
Hi,
No one is working on this as of now, you can go ahead and give it a try!
I have assigned it to you.

**Comment by dikshantsagar12** [comment]
I have added changes to the project but when pushing changes from my branch, I'm getting this error:
"remote: Permission to dikshantsagar12/Emoji-Cart-With-React.git denied to emicon-web."
Can you help me with this?

**Comment by JVJplus** [comment]
you might have logined with different github account, due to which it is getting error in pushing.

You can alternatively paste the code directly on github website, editing the src on website.
